version: "2.1"
orbs:
  go: circleci/go@3.0.0
jobs:
  build:
    executor:
      name: go/default
      tag: "1.23"
    steps:
      - checkout
      - go/with-cache
      - go/mod-download
      - go/test:
          covermode: atomic
          failfast: true
workflows:
  main:
    jobs:
      - build
